name: Auto Approve

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]' || github.actor == 'Lint Action'

    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto approved PR"
