name: Auto Approve

on: [push, pull_request_target]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]' || github.actor == 'Lint Action'

    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved PR"
