name: Build

env:
  sln-path: "./src/cellular automaton.sln"

on: 
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '!src/**.sln'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        dotnet-version: [ '2.0.x' ]

    # required by dorny/test-reporter
    permissions:
      contents: read  
      id-token: write
      checks: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .Net ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Dotnet Installation Info
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore "${{ env.sln-path }}"

    - name: Build
      run: dotnet build "${{ env.sln-path }}" --no-restore

    - name: Test
      run: dotnet test "${{ env.sln-path }}" --no-build --logger "trx;LogFileName=test-results.trx" || true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Tests ${{ matrix.dotnet-version }}
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true
