name: Build

env:
  sln-path: "./src/cellular automaton.sln"
  dotnet-version: "8.0.x"

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    # required by dorny/test-reporter
    permissions:
      contents: read
      id-token: write
      checks: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .Net ${{ env.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnet-version }}

    - name: Dotnet Installation Info
      run: dotnet --info

    - name: Restore dependencies
      run: dotnet restore "${{ env.sln-path }}"

    - name: Build
      run: dotnet build "${{ env.sln-path }}" --no-restore --configuration Release

    - name: Test
      run: dotnet test "${{ env.sln-path }}" --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Tests
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true
